[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bundle exec rails server -p $PORT"
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
